### ISSUE TITLE
PLS man use RUST!

### ISSUE THREAD

**Issue by icupken** [lilbudek/stm32f1_libopencm3#1]
dude, smart people doing this for you: https://github.com/stm32-rs/stm32f1xx-hal. Just use!
![rust_poster](https://github.com/lilbudek/stm32f1_libopencm3/assets/59444437/9f6b4a75-5c0b-4838-a1f1-77ab94f27ea7)

**Comment by lilbudek** [comment]
![ic5cukleewe81](https://github.com/lilbudek/stm32f1_libopencm3/assets/93509048/7ba75a3d-e75d-4271-9f93-f3829bce7a8c)
